#!/usr/bin/env python3
"""Generate curated API Markdown from Python docstrings (Griffe).

Run from repo root via docs prestart/prebuild:
  uv run python docs/scripts/generate-api.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any, Iterable

from griffe import (
    DocstringSectionKind,
    Function,
    Object,
    ParameterKind,
    load,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
API_DIR = REPO_ROOT / "docs" / "docs" / "api"

SEARCH_PATHS = [
    str(REPO_ROOT / "packages" / "core" / "src"),
    str(REPO_ROOT / "packages" / "instrumentation-livekit" / "src"),
    str(REPO_ROOT / "packages" / "instrumentation-langgraph" / "src"),
]

SHARED_CONFIGURE_PARAMS = frozenset(
    {
        "endpoint",
        "api_key",
        "capture_genai_content",
        "service_name",
        "tracer_provider",
        "agent_id",
        "version",
        "capture_logs",
        "log_level",
    }
)

GENERATED_BANNER = "<!-- Generated by docs/scripts/generate-api.py — do not edit by hand. -->"


def _rst_to_md(text: str, *, skip_examples: bool = False) -> str:
    """Light conversion of common reST / Google docstring markup to Markdown."""
    if not text:
        return ""
    # ``code`` → `code`
    text = re.sub(r"``([^`]+)``", r"`\1`", text)
    parts: list[str] = []
    for block in re.split(r"\n\n+", text.strip()):
        stripped = block.lstrip()
        if stripped.startswith("Example:") or stripped.startswith("Example::"):
            if skip_examples:
                continue
            # Drop the Example label; keep indented code as a fence below.
            continue
        if "\n    " in block or block.startswith("    "):
            if skip_examples:
                continue
            lines = [ln[4:] if ln.startswith("    ") else ln for ln in block.splitlines()]
            body = "\n".join(lines).strip()
            if body.startswith(("from ", "set_", "add_", "record_", "async ", "with ")):
                parts.append(f"```python\n{body}\n```")
            else:
                parts.append(body)
            continue
        # Preserve markdown list numbering / bullets (don't join onto one line).
        if re.match(r"^\d+\.\s", stripped) or stripped.startswith(("- ", "* ")):
            list_lines: list[str] = []
            for ln in block.splitlines():
                list_lines.append(ln.strip())
            parts.append("\n".join(list_lines))
            continue
        parts.append(" ".join(ln.strip() for ln in block.splitlines() if ln.strip()))
    return "\n\n".join(parts)


def _ann(obj: Any) -> str:
    if obj is None:
        return ""
    text = str(obj).replace("NoneType", "None")
    # Prefer modern union form for readability in docs.
    text = re.sub(r"Optional\[([^\]]+)\]", r"\1 | None", text)
    # Drop quotes around forward refs / string annotations.
    if len(text) >= 2 and text[0] in {"'", '"'} and text[-1] == text[0]:
        text = text[1:-1]
    return text


def _param_default(param: Any) -> str | None:
    """Return default expression string, or None when the parameter is required."""
    if getattr(param, "required", False):
        return None
    default = param.default
    if default is None:
        return "None"
    text = str(default)
    if text in {"", "empty"}:
        return None
    # Normalize string defaults: 'custom' → "custom"
    if len(text) >= 2 and text[0] == "'" and text[-1] == "'":
        text = f'"{text[1:-1]}"'
    return text


def _signature(fn: Function, *, only: frozenset[str] | None = None) -> str:
    """Render a Python signature. Uses keyword-only style when the function is kw-only."""
    params = [p for p in fn.parameters if p.name not in {"self", "cls"}]
    if only is not None:
        params = [
            p
            for p in params
            if p.name in only or p.kind == ParameterKind.var_keyword
        ]

    has_pos = any(
        p.kind
        in (ParameterKind.positional_only, ParameterKind.positional_or_keyword)
        for p in params
        if p.kind != ParameterKind.var_keyword
    )
    has_kw_only = any(p.kind == ParameterKind.keyword_only for p in params)

    lines = [f"def {fn.name}("]
    if has_kw_only and not has_pos:
        lines.append("    *,")

    saw_kw_separator = has_kw_only and not has_pos
    for param in params:
        if param.kind == ParameterKind.var_keyword:
            if only is None:
                name = param.name
                ann = _ann(param.annotation)
                if ann:
                    lines.append(f"    **{name}: {ann},")
                else:
                    lines.append(f"    **{name},")
            continue
        if only is not None and param.name not in only:
            continue
        if param.kind == ParameterKind.keyword_only and not saw_kw_separator and has_pos:
            lines.append("    *,")
            saw_kw_separator = True
        ann = _ann(param.annotation) or "Any"
        default = _param_default(param)
        if default is None:
            lines.append(f"    {param.name}: {ann},")
        else:
            lines.append(f"    {param.name}: {ann} = {default},")

    ret = _ann(fn.returns) or "None"
    lines.append(f") -> {ret}")
    return "\n".join(lines)


def _doc_sections(
    obj: Object, *, skip_examples: bool = True
) -> tuple[str, list[Any], list[Any]]:
    """Return (summary_md, parameters, returns)."""
    if not obj.docstring:
        return "", [], []
    parsed = (
        obj.docstring.parse("google")
        if obj.docstring.parser is None
        else obj.docstring.parsed
    )
    text_parts: list[str] = []
    params: list[Any] = []
    returns: list[Any] = []
    for section in parsed:
        if section.kind == DocstringSectionKind.text:
            text_parts.append(_rst_to_md(section.value, skip_examples=skip_examples))
        elif section.kind == DocstringSectionKind.parameters:
            params.extend(section.value)
        elif section.kind == DocstringSectionKind.other_parameters:
            params.extend(section.value)
        elif section.kind == DocstringSectionKind.returns:
            returns.extend(section.value)
    return "\n\n".join(p for p in text_parts if p), params, returns


def _params_table(
    params: Iterable[Any],
    *,
    fn: Function | None = None,
    only: frozenset[str] | None = None,
    exclude: frozenset[str] | None = None,
) -> str:
    rows: list[str] = [
        "| Parameter | Type | Default | Description |",
        "|-----------|------|---------|-------------|",
    ]
    sig_by_name = {}
    if fn is not None:
        for p in fn.parameters:
            sig_by_name[p.name] = p

    for doc_param in params:
        raw_name = doc_param.name
        clean = raw_name.replace("*", "")
        if only is not None and clean not in only:
            continue
        if exclude is not None and clean in exclude:
            continue
        if clean == "kwargs":
            continue

        sig = sig_by_name.get(clean)
        ann = (
            _ann(getattr(doc_param, "annotation", None))
            or (_ann(sig.annotation) if sig else "")
            or "—"
        )
        if sig is not None:
            default = _param_default(sig)
            default_cell = "—" if default is None else default
        else:
            default_cell = "—"
        desc = _rst_to_md(doc_param.description or "").replace("\n", " ")
        rows.append(f"| `{clean}` | `{ann}` | `{default_cell}` | {desc} |")

    if len(rows) == 2:
        return ""
    return "\n".join(rows)


def _returns_md(returns: list[Any]) -> str:
    if not returns:
        return ""
    parts = [_rst_to_md(r.description or "") for r in returns if r.description]
    body = " ".join(p for p in parts if p)
    return f"**Returns:** {body}" if body else ""


def _render_function(
    fn: Function,
    *,
    heading: str | None = None,
    only_params: frozenset[str] | None = None,
    exclude_params: frozenset[str] | None = None,
    note: str | None = None,
    example: str | None = None,
) -> str:
    title = heading or f"`{fn.name}()`"
    summary, params, returns = _doc_sections(fn)
    chunks = [f"### {title}", "", f"```python\n{_signature(fn, only=only_params)}\n```", ""]
    if note:
        chunks.extend([note, ""])
    if summary:
        chunks.extend([summary, ""])
    table = _params_table(params, fn=fn, only=only_params, exclude=exclude_params)
    if table:
        chunks.extend(["#### Parameters", "", table, ""])
    ret = _returns_md(returns)
    if ret:
        chunks.extend([ret, ""])
    if example:
        chunks.extend(["#### Example", "", f"```python\n{example.strip()}\n```", ""])
    return "\n".join(chunks).rstrip() + "\n"


def _render_class(obj: Object, *, heading: str | None = None) -> str:
    title = heading or f"`{obj.name}`"
    summary, _, _ = _doc_sections(obj)
    chunks = [f"### {title}", ""]
    if summary:
        chunks.extend([summary, ""])
    return "\n".join(chunks).rstrip() + "\n"


def _front_matter(**fields: Any) -> str:
    lines = ["---"]
    for key, value in fields.items():
        if isinstance(value, dict):
            lines.append(f"{key}:")
            for k, v in value.items():
                lines.append(f"  {k}: {v}")
        else:
            lines.append(f"{key}: {value}")
    lines.append("---")
    return "\n".join(lines)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {path.relative_to(REPO_ROOT)}")


def generate_configure() -> None:
    mod = load(
        "parlot.core.configure",
        search_paths=SEARCH_PATHS,
        docstring_parser="google",
    )
    proto = mod["ConfigureProtocol"]
    call = proto.members["__call__"]
    _, params, _ = _doc_sections(call)

    # Prefer documenting the shared surface from ConfigureProtocol Args,
    # with types/defaults from base_configure where available.
    base = mod["base_configure"]
    # service_name is on the protocol but not base_configure — synthesize from livekit.
    lk = load(
        "parlot.instrumentation.livekit._auto",
        search_paths=SEARCH_PATHS,
        docstring_parser="google",
    )
    lk_cfg = lk["configure"]

    # Build a synthetic signature listing shared params only.
    sig_lines = [
        "# Shared keyword surface (every adapter configure())",
        "def configure(",
        "    *,",
    ]
    for name in (
        "endpoint",
        "api_key",
        "capture_genai_content",
        "service_name",
        "tracer_provider",
        "agent_id",
        "version",
        "capture_logs",
        "log_level",
    ):
        param = None
        for candidate in (lk_cfg, base):
            for p in candidate.parameters:
                if p.name == name:
                    param = p
                    break
            if param:
                break
        if param is None:
            continue
        ann = _ann(param.annotation) or "Any"
        default = _param_default(param)
        if default is None:
            sig_lines.append(f"    {name}: {ann},")
        else:
            sig_lines.append(f"    {name}: {ann} = {default},")
    sig_lines.append(") -> ParlotContext")
    signature = "\n".join(sig_lines)

    table = _params_table(params, fn=lk_cfg, only=SHARED_CONFIGURE_PARAMS)

    # Prefer Args descriptions; drop the short Protocol class blurb.
    intro = (
        "Common keyword-only options every adapter `configure()` accepts. "
        "Framework packages may add extras (documented on each adapter page)."
    )

    body = f"""{_front_matter(
        title="configure()",
        description="Shared configure() keyword surface across Parlot adapters.",
        sidebar_position=2,
        sidebar_custom_props={"eyebrow": "Shared"},
    )}

{GENERATED_BANNER}

# `configure()` — shared options

Every adapter (`parlot.instrumentation.livekit.configure`,
`parlot.instrumentation.langgraph.configure`, …) accepts the same keyword-only
core options. Framework packages may add extras (e.g. LiveKit `record=`,
LangGraph `channel=`) — those are documented on each adapter's API page.

{intro}

```python
{signature}
```

## Parameters

{table}

## Precedence

When both environment variables and programmatic arguments are provided, policy
resolution generally follows:

1. **Job / context metadata** (e.g. LiveKit job metadata)
2. **`configure(...)` arguments**
3. **`PARLOT_*` environment variables**
4. **Remote telemetry bootstrap** (Parlot Settings UI)
5. **SDK defaults** (GenAI content capture and session logs default **on**)

See [Environment Variables](./env-vars.md) for the full env reference.

## Adapter-specific options

- [LiveKit API](./livekit.md) — `record`, `auto_escalate_sip`, `escalation_metadata_match`
- [LangGraph API](./langgraph.md) — `channel`, `modality`
"""
    _write(API_DIR / "configure.md", body)


def generate_livekit() -> None:
    mod = load(
        "parlot.instrumentation.livekit._auto",
        search_paths=SEARCH_PATHS,
        docstring_parser="google",
    )
    events = load(
        "parlot.instrumentation.livekit._events",
        search_paths=SEARCH_PATHS,
        docstring_parser="google",
    )
    proc = load(
        "parlot.instrumentation.livekit._processor",
        search_paths=SEARCH_PATHS,
        docstring_parser="google",
    )
    cfg = mod["configure"]
    extras = frozenset(
        {"record", "auto_escalate_sip", "escalation_metadata_match"}
    )

    configure_block = _render_function(
        cfg,
        heading="`configure()`",
        only_params=extras,
        exclude_params=SHARED_CONFIGURE_PARAMS,
        note=(
            "Shared options (`endpoint`, `api_key`, `agent_id`, `version`, "
            "`capture_genai_content`, `capture_logs`, `log_level`, `service_name`, "
            "`tracer_provider`) are documented on the "
            "[shared `configure()` page](./configure.md)."
        ),
        example="""\
from parlot.instrumentation.livekit import configure

# Call before initializing AgentSession or starting workers
configure(
    agent_id="receptionist-v2",
    version="1.4.0",
    record=True,
    capture_logs=True,
    log_level="INFO",
)""",
    )

    # Show full signature in a collapsed sense: regenerate with all params for the code fence.
    full_sig = _signature(cfg)
    summary, params, returns = _doc_sections(cfg)
    extras_table = _params_table(params, fn=cfg, only=extras)
    ret = _returns_md(returns)

    hooks = events["install_session_hooks"]
    hooks_block = _render_function(hooks)

    processor = proc["LiveKitGenAIProcessor"]
    processor_block = _render_class(processor)

    body = f"""{_front_matter(
        title="LiveKit API",
        description="API reference for parlot-instrumentation-livekit.",
        sidebar_position=3,
        sidebar_custom_props={"eyebrow": "Framework"},
    )}

{GENERATED_BANNER}

# LiveKit API Reference

`parlot-instrumentation-livekit` provides OpenTelemetry instrumentation, auto-patching, and session recording hooks for [LiveKit Agents](https://docs.livekit.io/agents/).

## Installation

```bash
# Using pip
pip install parlot-instrumentation-livekit
# or with meta-package:
pip install "parlot[livekit]"

# Using uv
uv add parlot-instrumentation-livekit
```

## Module: `parlot.instrumentation.livekit`

### `configure()`

```python
{full_sig}
```

{summary}

Shared options (`endpoint`, `api_key`, `agent_id`, `version`, `capture_genai_content`,
`capture_logs`, `log_level`, `service_name`, `tracer_provider`) are documented on the
[shared `configure()` page](./configure.md). LiveKit-only parameters:

#### LiveKit-only parameters

{extras_table}

{ret}

#### Example

```python
from parlot.instrumentation.livekit import configure

# Call before initializing AgentSession or starting workers
configure(
    agent_id="receptionist-v2",
    version="1.4.0",
    record=True,
    capture_logs=True,
    log_level="INFO",
)
```

---

{hooks_block}

---

{processor_block}

---

## Re-exported Core Functions

`parlot.instrumentation.livekit` re-exports common session helpers from `parlot-core`:

- [`set_session_metadata(**pairs)`](./core.md#set_session_metadata)
- [`set_session_attribute(key, value)`](./core.md#set_session_attribute)
- [`add_platform_ref(kind, value, framework="custom")`](./core.md#add_platform_ref)
- [`record_human_rep(participant_id, label=None)`](./core.md#record_human_rep)
- [`human_escalation(label=None)`](./core.md#human_escalation)
"""
    # configure_block unused after inlining — keep generation focused.
    del configure_block
    _write(API_DIR / "livekit.md", body)


def generate_langgraph() -> None:
    mod = load(
        "parlot.instrumentation.langgraph._auto",
        search_paths=SEARCH_PATHS,
        docstring_parser="google",
    )
    cb = load(
        "parlot.instrumentation.langgraph._callbacks",
        search_paths=SEARCH_PATHS,
        docstring_parser="google",
    )
    cfg = mod["configure"]
    close = mod["close_session"]
    extras = frozenset({"channel", "modality"})

    full_sig = _signature(cfg)
    summary, params, returns = _doc_sections(cfg)
    extras_table = _params_table(params, fn=cfg, only=extras)
    ret = _returns_md(returns)
    close_block = _render_function(
        close,
        example="""\
from parlot.instrumentation.langgraph import configure, close_session

configure(agent_id="support-bot")

graph.invoke(
    {"messages": [("user", "What is my balance?")]},
    config={"configurable": {"thread_id": "session-xyz"}},
)

close_session("session-xyz", reason="completed")""",
    )
    handler = _render_class(cb["ParlotLangGraphCallbackHandler"])

    body = f"""{_front_matter(
        title="LangGraph API",
        description="API reference for parlot-instrumentation-langgraph.",
        sidebar_position=4,
        sidebar_custom_props={"eyebrow": "Framework"},
    )}

{GENERATED_BANNER}

# LangGraph API Reference

`parlot-instrumentation-langgraph` provides OpenTelemetry instrumentation for LangGraph and LangChain agents. It registers a global callback handler so that all graph invocations emit Parlot Conversation Contract spans and OTel GenAI (v1.41.0) spans automatically.

## Installation

```bash
# Using pip
pip install parlot-instrumentation-langgraph
# or with meta-package:
pip install "parlot[langgraph]"

# Using uv
uv add parlot-instrumentation-langgraph
```

## Module: `parlot.instrumentation.langgraph`

### `configure()`

```python
{full_sig}
```

{summary}

Shared options (`endpoint`, `api_key`, `agent_id`, `version`, `capture_genai_content`,
`capture_logs`, `log_level`, `service_name`, `tracer_provider`) are documented on the
[shared `configure()` page](./configure.md). LangGraph-only parameters:

#### LangGraph-only parameters

{extras_table}

{ret}

#### Example

```python
from parlot.instrumentation.langgraph import configure

configure(
    agent_id="customer-support-graph",
    version="2.1.0",
    channel="webchat",
    modality="text",
)
```

---

{close_block}

---

{handler}

---

## LiveKit + LangGraph Coexistence

When using LangGraph inside a LiveKit voice agent (via `livekit.plugins.langchain.LLMAdapter`), initialize both adapters:

```python
from parlot.instrumentation.livekit import configure as configure_livekit
from parlot.instrumentation.langgraph import configure as configure_langgraph

# 1. LiveKit configuration initializes the main tracer provider
configure_livekit(agent_id="voice-bot", version="1.0.0")

# 2. LangGraph configuration automatically adopts the active TracerProvider
configure_langgraph()
```

- **Contract ownership:** LiveKit owns `parlot.session`, `parlot.turn`, and audio recording.
- **Nested GenAI spans:** LangGraph emits granular LLM and tool spans nested cleanly beneath LiveKit's turn context.
- **Zero span duplication:** LangGraph suppresses redundant session/turn contract spans when LiveKit is active.

---

## Re-exported Core Functions

`parlot.instrumentation.langgraph` re-exports common session helpers from `parlot-core`:

- [`set_session_metadata(**pairs)`](./core.md#set_session_metadata)
- [`set_session_attribute(key, value)`](./core.md#set_session_attribute)
- [`add_platform_ref(kind, value, framework="custom")`](./core.md#add_platform_ref)
- [`stamp_platform_refs(span, refs)`](./core.md#stamp_platform_refs)
- [`record_human_rep(participant_id, label=None)`](./core.md#record_human_rep)
- [`human_escalation(label=None)`](./core.md#human_escalation)
"""
    _write(API_DIR / "langgraph.md", body)


ATTRS_SECTION = """
## Semantic Convention Constants (`parlot.core.attrs`)

`parlot.core.attrs` exports all attribute, span, and metric name constants:

### Spans (`CONTRACT_SPAN_NAMES`)

```python
SPAN_CONVERSATION_SESSION = "parlot.session"
SPAN_PARLOT_TURN          = "parlot.turn"
SPAN_PARLOT_SESSION_CLOSE = "parlot.session.close"
SPAN_AGENT_HANDOFF        = "parlot.agent.handoff"

# Voice Operational Spans
SPAN_VOICE_TTS = "tts"
SPAN_VOICE_STT = "stt"
SPAN_VOICE_EOU = "eou_detection"
SPAN_VOICE_AMD = "amd"

# GenAI Operations (OTel SemConv v1.41.0)
SPAN_GEN_AI_CHAT            = "chat"
SPAN_GEN_AI_EXECUTE_TOOL    = "execute_tool"
SPAN_GEN_AI_INVOKE_AGENT    = "invoke_agent"
SPAN_GEN_AI_INVOKE_WORKFLOW = "invoke_workflow"
```

### Key Attributes

| Constant | Attribute String | Description |
|----------|------------------|-------------|
| `ATTR_SESSION_ID` | `session.id` | Unique UUID v7 session identifier. |
| `ATTR_SESSION_CONVERSATION_ID` | `session.conversation_id` | Conversation grouping identifier. |
| `ATTR_SESSION_MODALITY` | `session.modality` | Interaction modality (`"voice"`, `"text"`, `"multimodal"`). |
| `ATTR_SESSION_AGENT_ID` | `session.agent_id` | Canonical deployment ID. |
| `ATTR_GEN_AI_AGENT_VERSION` | `gen_ai.agent.version` | Agent version string. |
| `ATTR_SESSION_METADATA_PREFIX` | `session.metadata.` | Prefix for custom user metadata keys. |
| `ATTR_PLATFORM_REF_PREFIX` | `platform.ref.` | Prefix for external reference keys. |
| `ATTR_GEN_AI_MODEL` | `gen_ai.request.model` | Model name. |
| `ATTR_GEN_AI_IN_TOKENS` | `gen_ai.usage.input_tokens` | Prompt/input tokens. |
| `ATTR_GEN_AI_OUT_TOKENS` | `gen_ai.usage.output_tokens` | Completion/output tokens. |
| `ATTR_GEN_AI_COST_USD` | `gen_ai.usage.cost_usd` | Incurred LLM cost in USD. |
"""


def generate_core() -> None:
    meta = load("parlot.core.metadata", search_paths=SEARCH_PATHS, docstring_parser="google")
    refs = load(
        "parlot.core.platform_refs", search_paths=SEARCH_PATHS, docstring_parser="google"
    )
    esc = load("parlot.core.escalation", search_paths=SEARCH_PATHS, docstring_parser="google")
    sess = load("parlot.core.session", search_paths=SEARCH_PATHS, docstring_parser="google")

    blocks = [
        _render_function(
            meta["set_session_metadata"],
            example="""\
from parlot.core import set_session_metadata

set_session_metadata(
    order_id="12345",
    crm_account_id="ACC-99",
    priority=1,
    is_vip=True,
)""",
        ),
        _render_function(
            meta["set_session_attribute"],
            example="""\
from parlot.core import set_session_attribute

set_session_attribute("cart_total_usd", 149.99)""",
        ),
        _render_function(
            refs["add_platform_ref"],
            example="""\
from parlot.core import add_platform_ref

add_platform_ref("crm_ticket", "TKT-8841")
add_platform_ref("stripe_customer_id", "cus_N9a8bc")""",
        ),
        _render_function(refs["stamp_platform_refs"]),
        _render_function(
            esc["record_human_rep"],
            example="""\
from parlot.core import record_human_rep

record_human_rep("agent_sarah_102", label="Senior Specialist")""",
        ),
        _render_function(
            esc["human_escalation"],
            example="""\
from parlot.core import human_escalation

async def transfer_call(dial_helper, target_number):
    with human_escalation(label="Escalations"):
        await dial_helper.dial(target_number)""",
        ),
        _render_function(sess["get_active_session"]),
        _render_function(sess["get_active_session_span"]),
        _render_function(sess["session_owned"]),
        _render_class(sess["SessionState"]),
    ]

    # Group headings to match prior structure
    metadata_section = "\n---\n\n".join(blocks[0:2])
    refs_section = "\n---\n\n".join(blocks[2:4])
    esc_section = "\n---\n\n".join(blocks[4:6])
    session_section = "\n---\n\n".join(blocks[6:10])

    body = f"""{_front_matter(
        title="Core & Session API",
        description="API reference for parlot-core semantic conventions, metadata, platform refs, and session helpers.",
        sidebar_position=5,
        sidebar_custom_props={"eyebrow": "Shared"},
    )}

{GENERATED_BANNER}

# Core & Session API Reference

`parlot-core` contains framework-agnostic session helpers, OpenTelemetry semantic conventions, and state context management.

These functions can be imported from `parlot.core` or directly from framework packages (`parlot.instrumentation.livekit` and `parlot.instrumentation.langgraph`).

---

## Session Metadata & Custom Attributes

{metadata_section}

---

## Platform References & Search Linking

{refs_section}

---

## Human Escalation & Roles

{esc_section}

---

## Session Context & State Access

Parlot tracks session state in thread/async-safe `contextvars`.

{session_section}

---

{ATTRS_SECTION.strip()}
"""
    _write(API_DIR / "core.md", body)


def update_api_index() -> None:
    """Ensure the API index mentions shared configure()."""
    index = API_DIR / "index.mdx"
    text = index.read_text(encoding="utf-8")
    needle = "- **Keyword-only configuration:**"
    addition = (
        "- **Shared `configure()` surface:** Common kwargs are documented once on "
        "[`configure()`](./configure.md); LiveKit and LangGraph pages cover extras only.\n"
    )
    if "./configure.md" in text:
        return
    if needle in text:
        text = text.replace(needle, addition + needle)
        index.write_text(text, encoding="utf-8")
        print(f"Updated {index.relative_to(REPO_ROOT)}")


def main() -> int:
    generate_configure()
    generate_livekit()
    generate_langgraph()
    generate_core()
    update_api_index()
    return 0


if __name__ == "__main__":
    sys.exit(main())
