#!/usr/bin/env bun
/**
 * Generate curated API Markdown from docs-data/api.json (Griffe AST).
 *
 * Run from docs directory:
 *   bun run scripts/generate-api.ts
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { cleanAnn, paramDefault } from "./lib/ast";

const DOCS_DIR = resolve(__dirname, "..");
const REPO_ROOT = resolve(DOCS_DIR, "..");
const API_DIR = resolve(DOCS_DIR, "docs/api");
const API_JSON_PATH = resolve(REPO_ROOT, "docs-data/api.json");

const GENERATED_BANNER =
  "<!-- Generated by docs/scripts/generate-api.ts — do not edit by hand. -->";

export function rstToMd(text: string, skipExamples = false): string {
  if (!text) return "";
  // ``code`` → `code`
  text = text.replace(/``([^`]+)``/g, "`$1`");
  const parts: string[] = [];
  const blocks = text.trim().split(/\n\n+/);
  for (const block of blocks) {
    const stripped = block.trimStart();
    if (stripped.startsWith("Example:") || stripped.startsWith("Example::")) {
      if (skipExamples) continue;
      continue;
    }
    if (block.includes("\n    ") || block.startsWith("    ")) {
      if (skipExamples) continue;
      const lines = block
        .split(/\r?\n/)
        .map((ln) => (ln.startsWith("    ") ? ln.slice(4) : ln));
      const body = lines.join("\n").trim();
      if (
        body.startsWith("from ") ||
        body.startsWith("set_") ||
        body.startsWith("add_") ||
        body.startsWith("record_") ||
        body.startsWith("async ") ||
        body.startsWith("with ")
      ) {
        parts.push(`\`\`\`python\n${body}\n\`\`\``);
      } else {
        parts.push(body);
      }
      continue;
    }
    // Preserve markdown list numbering / bullets (don't join onto one line).
    if (/^\d+\.\s/.test(stripped) || stripped.startsWith("- ") || stripped.startsWith("* ")) {
      const listLines = block
        .split(/\r?\n/)
        .map((ln) => ln.trim());
      parts.push(listLines.join("\n"));
      continue;
    }
    const joined = block
      .split(/\r?\n/)
      .map((ln) => ln.trim())
      .filter((ln) => ln.length > 0)
      .join(" ");
    if (joined) {
      parts.push(joined);
    }
  }
  return parts.join("\n\n");
}

export function signature(
  fn: any,
  options?: { only?: Set<string>; fnName?: string }
): string {
  const name = options?.fnName ?? fn.name;
  let params: any[] = (fn.parameters || []).filter(
    (p: any) => p.name !== "self" && p.name !== "cls"
  );
  if (options?.only) {
    params = params.filter(
      (p: any) => options.only!.has(p.name) || p.kind === "variadic keyword"
    );
  }

  const hasPos = params.some(
    (p: any) =>
      (p.kind === "positional-only" || p.kind === "positional or keyword") &&
      p.kind !== "variadic keyword"
  );
  const hasKwOnly = params.some((p: any) => p.kind === "keyword-only");

  const lines: string[] = [`def ${name}(`];
  if (hasKwOnly && !hasPos) {
    lines.push("    *,");
  }

  let sawKwSeparator = hasKwOnly && !hasPos;
  for (const param of params) {
    if (param.kind === "variadic keyword") {
      if (!options?.only) {
        const pName = param.name;
        const ann = cleanAnn(param.annotation);
        if (ann) {
          lines.push(`    **${pName}: ${ann},`);
        } else {
          lines.push(`    **${pName},`);
        }
      }
      continue;
    }
    if (options?.only && !options.only.has(param.name)) {
      continue;
    }
    if (param.kind === "keyword-only" && !sawKwSeparator && hasPos) {
      lines.push("    *,");
      sawKwSeparator = true;
    }
    const ann = cleanAnn(param.annotation) || "Any";
    const def = paramDefault(param);
    if (def === null) {
      lines.push(`    ${param.name}: ${ann},`);
    } else {
      lines.push(`    ${param.name}: ${ann} = ${def},`);
    }
  }

  const ret = cleanAnn(fn.returns) || "None";
  lines.push(`) -> ${ret}`);
  return lines.join("\n");
}

export function docSections(
  obj: any,
  options?: { skipExamples?: boolean }
): [string, any[], any[]] {
  const skipExamples = options?.skipExamples ?? true;
  if (!obj?.docstring) {
    return ["", [], []];
  }
  const parsed = obj.docstring.parsed || [];
  const textParts: string[] = [];
  const params: any[] = [];
  const returns: any[] = [];

  for (const section of parsed) {
    if (section.kind === "text") {
      textParts.push(rstToMd(section.value, skipExamples));
    } else if (
      section.kind === "parameters" ||
      section.kind === "other_parameters"
    ) {
      if (Array.isArray(section.value)) {
        params.push(...section.value);
      }
    } else if (section.kind === "returns") {
      if (Array.isArray(section.value)) {
        returns.push(...section.value);
      }
    }
  }

  return [textParts.filter(Boolean).join("\n\n"), params, returns];
}

export function paramsTable(
  params: any[],
  options?: {
    fn?: any;
    only?: Set<string>;
    exclude?: Set<string>;
  }
): string {
  const rows: string[] = [
    "| Parameter | Type | Default | Description |",
    "|-----------|------|---------|-------------|",
  ];
  const sigByName = new Map<string, any>();
  if (options?.fn?.parameters) {
    for (const p of options.fn.parameters) {
      sigByName.set(p.name, p);
    }
  }

  for (const docParam of params) {
    const rawName = docParam.name ?? "";
    const clean = rawName.replace(/\*/g, "");
    if (options?.only && !options.only.has(clean)) continue;
    if (options?.exclude && options.exclude.has(clean)) continue;
    if (clean === "kwargs") continue;

    const sig = sigByName.get(clean);
    const ann =
      cleanAnn(docParam.annotation) ||
      (sig ? cleanAnn(sig.annotation) : "") ||
      "—";

    let defaultCell = "—";
    if (sig) {
      const def = paramDefault(sig);
      if (def !== null) {
        defaultCell = def;
      }
    }
    const desc = rstToMd(docParam.description || "").replace(/\n/g, " ");
    const safeAnn = ann.replace(/\|/g, "\\|");
    const safeDefault = defaultCell.replace(/\|/g, "\\|");
    const safeDesc = desc.replace(/\|/g, "\\|");
    rows.push(`| \`${clean}\` | \`${safeAnn}\` | \`${safeDefault}\` | ${safeDesc} |`);
  }

  if (rows.length === 2) return "";
  return rows.join("\n");
}

export function returnsMd(returns: any[]): string {
  if (!returns || returns.length === 0) return "";
  const parts = returns
    .filter((r) => r.description)
    .map((r) => rstToMd(r.description));
  const body = parts.filter(Boolean).join(" ");
  return body ? `**Returns:** ${body}` : "";
}

export function renderFunction(
  fn: any,
  options?: {
    heading?: string;
    onlyParams?: Set<string>;
    excludeParams?: Set<string>;
    note?: string;
    example?: string;
  }
): string {
  const title = options?.heading || `\`${fn.name}()\``;
  const [summary, params, returns] = docSections(fn);
  const chunks: string[] = [
    `### ${title}`,
    "",
    `\`\`\`python\n${signature(fn, { only: options?.onlyParams })}\n\`\`\``,
    "",
  ];
  if (options?.note) {
    chunks.push(options.note, "");
  }
  if (summary) {
    chunks.push(summary, "");
  }
  const table = paramsTable(params, {
    fn,
    only: options?.onlyParams,
    exclude: options?.excludeParams,
  });
  if (table) {
    chunks.push("#### Parameters", "", table, "");
  }
  const ret = returnsMd(returns);
  if (ret) {
    chunks.push(ret, "");
  }
  if (options?.example) {
    chunks.push("#### Example", "", `\`\`\`python\n${options.example.trim()}\n\`\`\``, "");
  }
  return chunks.join("\n").trimEnd() + "\n";
}

export function renderClass(obj: any, options?: { heading?: string }): string {
  const title = options?.heading || `\`${obj.name}\``;
  const [summary] = docSections(obj);
  const chunks: string[] = [`### ${title}`, ""];
  if (summary) {
    chunks.push(summary, "");
  }
  return chunks.join("\n").trimEnd() + "\n";
}

export function frontMatter(fields: Record<string, any>): string {
  const lines: string[] = ["---"];
  for (const [key, value] of Object.entries(fields)) {
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      lines.push(`${key}:`);
      for (const [k, v] of Object.entries(value)) {
        lines.push(`  ${k}: ${v}`);
      }
    } else {
      lines.push(`${key}: ${value}`);
    }
  }
  lines.push("---");
  return lines.join("\n");
}

function write(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content.trimEnd() + "\n", "utf-8");
  console.log(`Wrote ${relative(REPO_ROOT, path)}`);
}

export function generateConfigure(data: any, sharedParams: Set<string>): void {
  const proto = data["parlot.core.configure"].members.ConfigureProtocol;
  const call = proto.members.__call__;
  const [, params] = docSections(call);

  let sig = signature(call, { only: sharedParams, fnName: "configure" });

  const table = paramsTable(params, { fn: call, only: sharedParams });

  const body = `${frontMatter({
    title: "configure()",
    description: "Shared configure() keyword surface across Parlot adapters.",
    sidebar_position: 2,
    sidebar_custom_props: { eyebrow: "Shared" },
  })}

${GENERATED_BANNER}

# \`configure()\` — shared options

Every adapter (\`parlot.instrumentation.livekit.configure\`,
\`parlot.instrumentation.langgraph.configure\`, …) accepts the same keyword-only
core options. Framework packages may add extras (e.g. LiveKit \`record=\`,
LangGraph \`channel=\`) — those are documented on each adapter's API page.

Common keyword-only options every adapter \`configure()\` accepts. Framework packages may add extras (documented on each adapter page).

\`\`\`python
# Shared keyword surface (every adapter configure())
${sig}
\`\`\`

## Parameters

${table}

## Precedence

Configuration values resolve in strict order:

1. **Job metadata / runtime context:** Explicit options passed at run/job start
   (e.g. LiveKit worker job metadata).
2. **\`configure()\` kwargs:** Parameters passed directly to \`configure()\` in
   code.
3. **Environment variables:** Standard \`PARLOT_*\` variables (see
   [Environment Variables](./env-vars.md)).
4. **Remote bootstrap:** Dynamic settings fetched from the Parlot platform at
   startup when \`api_key\` is present (recording policy, GenAI content capture,
   log streaming).
5. **Defaults:** Safe fallbacks (content capture enabled, INFO log level).

## Adapter-specific options

Each adapter extends this base surface with framework-specific parameters:

- [LiveKit Agent Options](./livekit.md#configure) — \`record\`,
  \`auto_escalate_sip\`, \`escalation_metadata_match\`
- [LangGraph Agent Options](./langgraph.md#configure) — \`channel\`, \`modality\`
`;

  write(resolve(API_DIR, "configure.md"), body);
}

export function generateLivekit(data: any, sharedParams: Set<string>): void {
  const mod = data["parlot.instrumentation.livekit._auto"];
  const events = data["parlot.instrumentation.livekit._events"];
  const proc = data["parlot.instrumentation.livekit._processor"];

  const cfg = mod.members.configure;
  // Programmatically extract adapter-only parameters
  const extras = new Set<string>(
    (cfg.parameters || [])
      .map((p: any) => p.name)
      .filter((name: string) => !sharedParams.has(name) && name !== "kwargs")
  );

  const fullSig = signature(cfg);
  const [summary, params, returns] = docSections(cfg);
  const extrasTable = paramsTable(params, { fn: cfg, only: extras });
  const ret = returnsMd(returns);

  const hooksBlock = renderFunction(events.members.install_session_hooks);
  const procBlock = renderClass(proc.members.LiveKitGenAIProcessor);

  const body = `${frontMatter({
    title: "LiveKit API",
    description: "API reference for parlot-instrumentation-livekit.",
    sidebar_position: 3,
    sidebar_custom_props: { eyebrow: "Framework" },
  })}

${GENERATED_BANNER}

# LiveKit API Reference

\`parlot-instrumentation-livekit\` provides OpenTelemetry instrumentation, auto-patching, and session recording hooks for [LiveKit Agents](https://docs.livekit.io/agents/).

## Installation

\`\`\`bash
# Using pip
pip install parlot-instrumentation-livekit
# or with meta-package:
pip install "parlot[livekit]"

# Using uv
uv add parlot-instrumentation-livekit
\`\`\`

## Module: \`parlot.instrumentation.livekit\`

### \`configure()\`

\`\`\`python
${fullSig}
\`\`\`

${summary}

Shared options (\`endpoint\`, \`api_key\`, \`agent_id\`, \`version\`, \`capture_genai_content\`,
\`capture_logs\`, \`log_level\`, \`service_name\`, \`tracer_provider\`) are documented on the
[shared \`configure()\` page](./configure.md). LiveKit-only parameters:

#### LiveKit-only parameters

${extrasTable}

${ret}

#### Example

\`\`\`python
from parlot.instrumentation.livekit import configure

# Call before initializing AgentSession or starting workers
configure(
    agent_id="receptionist-v2",
    version="1.4.0",
    record=True,
    auto_escalate_sip=True,
)
\`\`\`

---

${hooksBlock}

---

${procBlock}

---

## LiveKit + LangGraph Coexistence

When using LangGraph inside a LiveKit voice agent (via \`livekit.plugins.langchain.LLMAdapter\`), initialize both adapters:

\`\`\`python
from parlot.instrumentation.livekit import configure as configure_livekit
from parlot.instrumentation.langgraph import configure as configure_langgraph

# 1. LiveKit configuration initializes the main tracer provider
configure_livekit(agent_id="voice-bot", version="1.0.0")

# 2. LangGraph configuration automatically adopts the active TracerProvider
configure_langgraph()
\`\`\`

- **Contract ownership:** LiveKit owns \`parlot.session\`, \`parlot.turn\`, and audio recording.
- **Nested GenAI spans:** LangGraph emits granular LLM and tool spans nested cleanly beneath LiveKit's turn context.
- **Zero span duplication:** LangGraph suppresses redundant session/turn contract spans when LiveKit is active.

---

## Re-exported Core Functions

\`parlot.instrumentation.livekit\` re-exports common session helpers from \`parlot-core\`:

- [\`set_session_metadata(**pairs)\`](./core.md#set_session_metadata)
- [\`set_session_attribute(key, value)\`](./core.md#set_session_attribute)
- [\`add_platform_ref(kind, value, framework="custom")\`](./core.md#add_platform_ref)
- [\`stamp_platform_refs(span, refs)\`](./core.md#stamp_platform_refs)
- [\`record_human_rep(participant_id, label=None)\`](./core.md#record_human_rep)
- [\`human_escalation(label=None)\`](./core.md#human_escalation)
`;

  write(resolve(API_DIR, "livekit.md"), body);
}

export function generateLanggraph(data: any, sharedParams: Set<string>): void {
  const mod = data["parlot.instrumentation.langgraph._auto"];
  const cb = data["parlot.instrumentation.langgraph._callbacks"];

  const cfg = mod.members.configure;
  const close = mod.members.close_session;
  // Programmatically extract adapter-only parameters
  const extras = new Set<string>(
    (cfg.parameters || [])
      .map((p: any) => p.name)
      .filter((name: string) => !sharedParams.has(name) && name !== "kwargs")
  );

  const fullSig = signature(cfg);
  const [summary, params, returns] = docSections(cfg);
  const extrasTable = paramsTable(params, { fn: cfg, only: extras });
  const ret = returnsMd(returns);

  const closeBlock = renderFunction(close, {
    example: `from parlot.instrumentation.langgraph import configure, close_session

configure(agent_id="support-bot")

graph.invoke(
    {"messages": [("user", "What is my balance?")]},
    config={"configurable": {"thread_id": "session-xyz"}},
)

close_session("session-xyz", reason="completed")`,
  });

  const handler = renderClass(cb.members.ParlotLangGraphCallbackHandler);

  const body = `${frontMatter({
    title: "LangGraph API",
    description: "API reference for parlot-instrumentation-langgraph.",
    sidebar_position: 4,
    sidebar_custom_props: { eyebrow: "Framework" },
  })}

${GENERATED_BANNER}

# LangGraph API Reference

\`parlot-instrumentation-langgraph\` provides OpenTelemetry instrumentation for LangGraph and LangChain agents. It registers a global callback handler so that all graph invocations emit Parlot Conversation Contract spans and OTel GenAI (v1.41.0) spans automatically.

## Installation

\`\`\`bash
# Using pip
pip install parlot-instrumentation-langgraph
# or with meta-package:
pip install "parlot[langgraph]"

# Using uv
uv add parlot-instrumentation-langgraph
\`\`\`

## Module: \`parlot.instrumentation.langgraph\`

### \`configure()\`

\`\`\`python
${fullSig}
\`\`\`

${summary}

Shared options (\`endpoint\`, \`api_key\`, \`agent_id\`, \`version\`, \`capture_genai_content\`,
\`capture_logs\`, \`log_level\`, \`service_name\`, \`tracer_provider\`) are documented on the
[shared \`configure()\` page](./configure.md). LangGraph-only parameters:

#### LangGraph-only parameters

${extrasTable}

${ret}

#### Example

\`\`\`python
from parlot.instrumentation.langgraph import configure

configure(
    agent_id="customer-support-graph",
    version="2.1.0",
    channel="webchat",
    modality="text",
)
\`\`\`

---

${closeBlock}

---

${handler}

---

## LiveKit + LangGraph Coexistence

When using LangGraph inside a LiveKit voice agent (via \`livekit.plugins.langchain.LLMAdapter\`), initialize both adapters:

\`\`\`python
from parlot.instrumentation.livekit import configure as configure_livekit
from parlot.instrumentation.langgraph import configure as configure_langgraph

# 1. LiveKit configuration initializes the main tracer provider
configure_livekit(agent_id="voice-bot", version="1.0.0")

# 2. LangGraph configuration automatically adopts the active TracerProvider
configure_langgraph()
\`\`\`

- **Contract ownership:** LiveKit owns \`parlot.session\`, \`parlot.turn\`, and audio recording.
- **Nested GenAI spans:** LangGraph emits granular LLM and tool spans nested cleanly beneath LiveKit's turn context.
- **Zero span duplication:** LangGraph suppresses redundant session/turn contract spans when LiveKit is active.

---

## Re-exported Core Functions

\`parlot.instrumentation.langgraph\` re-exports common session helpers from \`parlot-core\`:

- [\`set_session_metadata(**pairs)\`](./core.md#set_session_metadata)
- [\`set_session_attribute(key, value)\`](./core.md#set_session_attribute)
- [\`add_platform_ref(kind, value, framework="custom")\`](./core.md#add_platform_ref)
- [\`stamp_platform_refs(span, refs)\`](./core.md#stamp_platform_refs)
- [\`record_human_rep(participant_id, label=None)\`](./core.md#record_human_rep)
- [\`human_escalation(label=None)\`](./core.md#human_escalation)
`;

  write(resolve(API_DIR, "langgraph.md"), body);
}

const ATTRS_SECTION = `## Semantic Convention Constants (\`parlot.core.attrs\`)

\`parlot.core.attrs\` exports all attribute, span, and metric name constants:

### Spans (\`CONTRACT_SPAN_NAMES\`)

\`\`\`python
SPAN_CONVERSATION_SESSION = "parlot.session"
SPAN_PARLOT_TURN          = "parlot.turn"
SPAN_PARLOT_SESSION_CLOSE = "parlot.session.close"
SPAN_AGENT_HANDOFF        = "parlot.agent.handoff"

# Voice Operational Spans
SPAN_VOICE_TTS = "tts"
SPAN_VOICE_STT = "stt"
SPAN_VOICE_EOU = "eou_detection"
SPAN_VOICE_AMD = "amd"

# GenAI Operations (OTel SemConv v1.41.0)
SPAN_GEN_AI_CHAT            = "chat"
SPAN_GEN_AI_EXECUTE_TOOL    = "execute_tool"
SPAN_GEN_AI_INVOKE_AGENT    = "invoke_agent"
SPAN_GEN_AI_INVOKE_WORKFLOW = "invoke_workflow"
\`\`\`

### Key Attributes

| Constant | Attribute String | Description |
|----------|------------------|-------------|
| \`ATTR_SESSION_ID\` | \`session.id\` | Unique UUID v7 session identifier. |
| \`ATTR_SESSION_CONVERSATION_ID\` | \`session.conversation_id\` | Conversation grouping identifier. |
| \`ATTR_SESSION_MODALITY\` | \`session.modality\` | Interaction modality (\`"voice"\`, \`"text"\`, \`"multimodal"\`). |
| \`ATTR_SESSION_AGENT_ID\` | \`session.agent_id\` | Canonical deployment ID. |
| \`ATTR_GEN_AI_AGENT_VERSION\` | \`gen_ai.agent.version\` | Agent version string. |
| \`ATTR_SESSION_METADATA_PREFIX\` | \`session.metadata.\` | Prefix for custom user metadata keys. |
| \`ATTR_PLATFORM_REF_PREFIX\` | \`platform.ref.\` | Prefix for external reference keys. |
| \`ATTR_GEN_AI_MODEL\` | \`gen_ai.request.model\` | Model name. |
| \`ATTR_GEN_AI_IN_TOKENS\` | \`gen_ai.usage.input_tokens\` | Prompt/input tokens. |
| \`ATTR_GEN_AI_OUT_TOKENS\` | \`gen_ai.usage.output_tokens\` | Completion/output tokens. |
| \`ATTR_GEN_AI_COST_USD\` | \`gen_ai.usage.cost_usd\` | Incurred LLM cost in USD. |`;

export function generateCore(data: any): void {
  const meta = data["parlot.core.metadata"];
  const refs = data["parlot.core.platform_refs"];
  const esc = data["parlot.core.escalation"];
  const sess = data["parlot.core.session"];

  const blocks = [
    renderFunction(meta.members.set_session_metadata, {
      example: `from parlot.core import set_session_metadata

set_session_metadata(
    order_id="12345",
    crm_account_id="ACC-99",
    priority=1,
    is_vip=True,
)`,
    }),
    renderFunction(meta.members.set_session_attribute, {
      example: `from parlot.core import set_session_attribute

set_session_attribute("cart_total_usd", 149.99)`,
    }),
    renderFunction(refs.members.add_platform_ref, {
      example: `from parlot.core import add_platform_ref

add_platform_ref("crm_ticket", "TKT-8841")
add_platform_ref("stripe_customer_id", "cus_N9a8bc")`,
    }),
    renderFunction(refs.members.stamp_platform_refs),
    renderFunction(esc.members.record_human_rep, {
      example: `from parlot.core import record_human_rep

record_human_rep("agent_sarah_102", label="Senior Specialist")`,
    }),
    renderFunction(esc.members.human_escalation, {
      example: `from parlot.core import human_escalation

async def transfer_call(dial_helper, target_number):
    with human_escalation(label="Escalations"):
        await dial_helper.dial(target_number)`,
    }),
    renderFunction(sess.members.get_active_session),
    renderFunction(sess.members.get_active_session_span),
    renderFunction(sess.members.session_owned),
    renderClass(sess.members.SessionState),
  ];

  const metadataSection = blocks.slice(0, 2).join("\n---\n\n");
  const refsSection = blocks.slice(2, 4).join("\n---\n\n");
  const escSection = blocks.slice(4, 6).join("\n---\n\n");
  const sessionSection = blocks.slice(6, 10).join("\n---\n\n");

  const body = `${frontMatter({
    title: "Core & Session API",
    description:
      "API reference for parlot-core semantic conventions, metadata, platform refs, and session helpers.",
    sidebar_position: 5,
    sidebar_custom_props: { eyebrow: "Shared" },
  })}

${GENERATED_BANNER}

# Core & Session API Reference

\`parlot-core\` contains framework-agnostic session helpers, OpenTelemetry semantic conventions, and state context management.

These functions can be imported from \`parlot.core\` or directly from framework packages (\`parlot.instrumentation.livekit\` and \`parlot.instrumentation.langgraph\`).

---

## Session Metadata & Custom Attributes

${metadataSection}

---

## Platform References & Search Linking

${refsSection}

---

## Human Escalation & Roles

${escSection}

---

## Session Context & State Access

Parlot tracks session state in thread/async-safe \`contextvars\`.

${sessionSection}

---

${ATTRS_SECTION.trim()}
`;

  write(resolve(API_DIR, "core.md"), body);
}

export function updateApiIndex(): void {
  const index = resolve(API_DIR, "index.mdx");
  let text = readFileSync(index, "utf-8");
  const needle = "- **Keyword-only configuration:**";
  const addition =
    "- **Shared `configure()` surface:** Common kwargs are documented once on " +
    "[`configure()`](./configure.md); LiveKit and LangGraph pages cover extras only.\n";
  if (text.includes("./configure.md")) {
    return;
  }
  if (text.includes(needle)) {
    text = text.replace(needle, addition + needle);
    writeFileSync(index, text, "utf-8");
    console.log(`Updated ${relative(REPO_ROOT, index)}`);
  }
}

export function main(): void {
  if (!readFileSync(API_JSON_PATH, "utf-8")) {
    throw new Error(`Missing ${API_JSON_PATH}`);
  }
  const data = JSON.parse(readFileSync(API_JSON_PATH, "utf-8"));

  // Programmatically extract the shared configure() parameter list
  const proto = data["parlot.core.configure"].members.ConfigureProtocol;
  const call = proto.members.__call__;
  const sharedParams = new Set<string>(
    call.parameters
      .map((p: any) => p.name)
      .filter(
        (name: string) => name !== "self" && name !== "cls" && name !== "kwargs"
      )
  );

  generateConfigure(data, sharedParams);
  generateLivekit(data, sharedParams);
  generateLanggraph(data, sharedParams);
  generateCore(data);
  updateApiIndex();
}

if (import.meta.main) {
  main();
}
