#!/usr/bin/env bash
# Generate docs/docs/changelog.md from package CHANGELOGs.
# Run via docs package prebuild / prestart (or manually: bash scripts/sync-changelog.sh).
set -euo pipefail

DOCS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "${DOCS_ROOT}/.." && pwd)"
OUT="${DOCS_ROOT}/content/docs/sdk/changelog.md"

packages=(
  "meta:parlot"
  "instrumentation-livekit:parlot-instrumentation-livekit"
  "instrumentation-langgraph:parlot-instrumentation-langgraph"
  "core:parlot-core"
)

{
  cat <<'EOF'
---
title: Changelog
description: Parlot SDK package release notes.
sidebar_position: 10
---

<!-- Generated by docs/scripts/sync-changelog.sh — do not edit by hand. -->

# Changelog
EOF

  for entry in "${packages[@]}"; do
    pkg_dir="${entry%%:*}"
    pkg_name="${entry##*:}"
    src="${REPO_ROOT}/packages/${pkg_dir}/CHANGELOG.md"
    if [[ -f "$src" ]]; then
      body="$(awk '
        BEGIN { seen_h1 = 0 }
        /^# / {
          if (!seen_h1) { seen_h1 = 1; next }
        }
        { print }
      ' "$src" | sed -E 's/^(#+)/\1#/')"

      printf '\n## %s\n\n%s\n' "$pkg_name" "$body"
    fi
  done
} >"${OUT}"

echo "Synced changelog -> content/docs/sdk/changelog.md"
