#!/usr/bin/env bash
# Generate docs/docs/changelog.md from packages/instrumentation-livekit/CHANGELOG.md.
# Run via docs package prebuild / prestart (or manually: bash scripts/sync-changelog.sh).
set -euo pipefail

DOCS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "${DOCS_ROOT}/.." && pwd)"
SRC="${REPO_ROOT}/packages/instrumentation-livekit/CHANGELOG.md"
OUT="${DOCS_ROOT}/docs/changelog.md"

if [[ ! -f "$SRC" ]]; then
  echo "error: missing package changelog at $SRC" >&2
  exit 1
fi

# Drop the package H1 (# Changelog), then demote remaining headings one level
# so they nest under ## instrumentation-livekit on the docs page.
body="$(awk '
  BEGIN { seen_h1 = 0 }
  /^# / {
    if (!seen_h1) { seen_h1 = 1; next }
  }
  { print }
' "$SRC" | sed -E 's/^(#+)/\1#/')"

{
  cat <<'EOF'
---
title: Changelog
description: Parlot SDK package release notes.
sidebar_position: 10
---

<!-- Generated by docs/scripts/sync-changelog.sh — do not edit by hand. -->

# Changelog

## instrumentation-livekit

EOF
  printf '%s\n' "$body"
} >"${OUT}"

echo "Synced changelog -> docs/docs/changelog.md"
